# Generated by Django 3.0.7 on 2020-06-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='UserAccount',
        ),
    ]
