# Generated by Django 3.0.7 on 2020-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200616_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
