# Generated by Django 3.0.7 on 2020-06-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50)),
                ('current_mileage', models.IntegerField()),
                ('service_interval', models.DurationField()),
                ('next_service', models.DateTimeField()),
            ],
        ),
    ]
