# Generated by Django 3.0.7 on 2020-06-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarsModel',
            new_name='Cars',
        ),
    ]
