# Generated by Django 3.0.7 on 2020-06-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200613_2346'),
        ('cars', '0003_auto_20200614_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.UserAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
